version: '3.8'
services:
    php-environment:
        container_name: hiveGame
        build:
            context: ./src
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./src:/var/www/html/
        ports:
            - 8001:80
    db:
        container_name: hiveDatabase
        image: mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: hive
        ports:
            - "9906:3306"