pipeline {
    agent {label '!windows'}
    stages {
         stage('build') {
            steps {
                sh 'echo "Building..."'
            }
        }
        stage('SonarQube') {
            steps {
                script { scannerHome = tool 'sonarqube-ows-scanner' }
                withSonarQubeEnv('sonarqube-ows') {
                    sh "${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=hiveOws"
                }
            }
        }
    }
}
