pipeline {
    agent { label '!windows' }
    stages {
        stage('build') {
            steps {
                sh 'echo "Building..."'
                sh 'composer install'
            }
        }
        stage('SonarQube') {
            steps {
                script { scannerHome = tool 'scanner-sonar' }
                withSonarQubeEnv('SonarQube') {
                    sh """
                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=ows-sonarqube
                    """
                }
            }
        }
        stage('PHPUnit') {
            steps {
                sh '../vendor/bin/phpunit --configuration phpunit.xml'
            }
            post {
                always {
                    junit '../tests/_output/junit.xml'
                }
            }
        }
    }
}


